name:                liszt
version:             "0.1"
github:              "fumieval/liszt"
license:             BSD3
author:              "Fumiaki Kinoshita"
maintainer:          "fumiexcel@gmail.com"
copyright:           "Copyright (c) 2018 Fumiaki Kinoshita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Append only key-list database
category:            Database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fumieval/liszt#readme>

dependencies:
- base >= 4.7 && < 5
- cpu
- deepseq
- network
- bytestring
- directory
- exceptions
- filepath
- fsnotify
- sendfile
- transformers
- binary
- containers
- unordered-containers
- stm
- stm-delay
- winery
- reflection
- text
- scientific
- vector
- vector-th-unbox

library:
  source-dirs: src
  exposed-modules:
    - Database.Liszt
    - Database.Liszt.Tracker
    - Database.Liszt.Internal
    - Database.Liszt.Network

executables:
  lisztd:
    main: server.hs
    source-dirs:         app
    ghc-options:
    - -threaded -O2
    dependencies:
    - liszt
  liszt:
    main: client.hs
    source-dirs: app
    dependencies:
    - liszt

benchmarks:
  bench:
    main: bench.hs
    source-dirs: benchmarks
    ghc-options: -O2
    dependencies:
    - liszt
    - gauge
